from baselines.Heater import HEATER
from baselines.DropoutNet import DROPOUTNET
from baselines.DeepMusic import DEEPMUSIC
from baselines.MetaEmb import METAEMB
from baselines.MTPR import MTPR
from baselines.KNN import MAP_KNN
from baselines.CLCRec import CLCREC
from baselines.MLP import MLP
from baselines.GNN import GNN
from baselines.GAR import GAR
